name: Validate Vagrant Setup

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build-box:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Dependencies
        shell: sh
        run: |
          brew bundle --file Brewfile
          vagrant plugin install vagrant-vmware-desktop
      - name: Validate Vagrantfile Syntax
        shell: sh
        run: |
          vagrant validate