name: Validate Vagrant Setup

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build-box:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Install Dependencies
        shell: sh
        run: |
          brew bundle --file Brewfile
          vagrant plugin install vagrant-vmware-desktop
      - name: Validate Vagrantfile Syntax
        shell: sh
        run: |
          vagrant validate